### ISSUE TITLE
Any plans for updates?

### ISSUE THREAD

**Issue by neheb** [jiixyj/libudev-fbsd#2]
I recently tried updating usbutils from version 007 to 008 but unfortunately 008 introduces a libudev requirement. The configure script errors out because it needs version 196 while libudev-fbsd provides 143. Even after patching it out, there are a bunch of missing functions that cause the build to fail.

**Comment by jiixyj** [comment]
Have you tried libudev-devd (https://github.com/wulf7/libudev-devd/)? It should be more complete than this library. My main use case was to get libinput/wayland to work. I haven't really tried it with anything else.

**Comment by jiixyj** [comment]
You could also try this fork here:
https://github.com/FreeBSDDesktop/libudev-devd

This is the version in the FreeBSD ports tree.

**Comment by neheb** [comment]
Oh ok. I only asked since this is the only libudev library in OpenWrt's
packages repository.

**Comment by jiixyj** [comment]
Wow, this is interesting. I didn't even know that this lib would compile under anything that isn't FreeBSD. But it's good to see that people could use this as a base for their own stubs. :+1:

**Comment by mirko** [comment]
It does after some patching - I took the opportunity to create a pull request with the common changes.
There are a couple of more patches which are more OpenWrt specific though - also including some stubs to keep applications happy which might be worth taking over:
https://github.com/openwrt/packages/tree/master/libs/libudev-fbsd/patches

**Comment by jiixyj** [comment]
The library should happily compile under Linux/glibc now. I'll try to merge those other patches soon.
